INSERT INTO CATEGORY (DESCRIPTION) VALUES ('American');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('India');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('Mexican');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('Fast Food');

INSERT INTO unit_of_measure (DESCRIPTION) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (DESCRIPTION) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (DESCRIPTION) VALUES ('cup');
INSERT INTO unit_of_measure (DESCRIPTION) VALUES ('Pinch');
INSERT INTO unit_of_measure (DESCRIPTION) VALUES ('Ounce');
